### PR TITLE
Team1

### PR DESCRIPTION
**Pull request by andressiles**
Added Team 1 Proposal

### CODE REVIEW

**Comment by mariellenolasco** [comment]
What is the point of the robot? What is it's raison d' etre?

**Comment by mariellenolasco** [comment]
We get what the robot is trying to accomplish but for what purpose does the robot do these tasks?

**Comment by schigit** [comment]
The robot would be used like a time management tool; it can help someone keep track of how much time they spend on a browser or just online in general.

**Comment by andressiles** [comment]
Would you like us to add that into the proposal?

**Comment by mariellenolasco** [comment]
Follow the naming convention for the p2 proposal but otherwise looks good

**Review by mariellenolasco — APPROVED** [review]
looks good!

**Pull request merged**
